<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Admins-MacBook-Pro-2.local" ignored="0" name="Test" tests="9" failures="1" timestamp="04 Jul 2019 03:05:11 GMT" time="22.216" errors="0">
  <testcase name="addAddress" time="0.101" classname="com.june.july.batch.TestNgDemo2"/>
  <testcase name="addToCart" time="0.001" classname="com.june.july.batch.TestNgDemo2"/>
  <testcase name="logOut" time="0.01" classname="com.june.july.batch.TestNgDemo2">
    <failure type="java.lang.AssertionError" message="Fail...">
      <![CDATA[java.lang.AssertionError: Fail...
at com.june.july.batch.TestNgDemo2.logOut(TestNgDemo2.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- logOut -->
  <testcase name="paymentCOd" time="0.001" classname="com.june.july.batch.TestNgDemo2">
    <skipped/>
  </testcase> <!-- paymentCOd -->
  <testcase name="pdp" time="0.002" classname="com.june.july.batch.TestNgDemo2"/>
  <testcase name="plp" time="0.009" classname="com.june.july.batch.TestNgDemo2"/>
  <testcase name="searchProduct" time="0.001" classname="com.june.july.batch.TestNgDemo2"/>
  <testcase name="amazon" time="13.057" classname="com.june.july.batch.Reports2"/>
  <testcase name="amazon" time="18.402" classname="com.june.july.batch.Reports"/>
</testsuite> <!-- Test -->
